### ISSUE TITLE
desafio: empacotar bibliotecas

### ISSUE THREAD

**Issue by vcwild** [gusthawojunkes/jogo-pt-python#1]
Boa tarde @gusthawojunkes , curti muito o seu projeto. Verifiquei que foi codado totalmente monorepo.
Seria interessante voce empacotar cada seção do seu game em partes menores de bibliotecas de classes, objetos e funções, assim tornando o código mais legível e apreciável pela comunidade.
Se quiser pegar como exemplo, tenho um [projetinho no terminal python](https://github.com/vcwild/customscripts) que usa os mesmos princípios, porém com as bibliotecas empacotadas.

*E aí, topa o desafio?*

**Comment by gusthawojunkes** [comment]
Opa @vcwild!
Achei muito interessante a sua proposta e adorei seu projeto. Seu repositório vai ser bastante útil para me basear, muito obrigado!
Eu sou bem inciante quanto ao mundo da programação e vou procurar entender mais sobre esse empacotamento do jogo, assim que tiver um tempo vou dar uma brincada com esse código!
